export enum LINKS {
  DESIGN = 'https://github.com/tact-lang/docs/blob/main/tact-design.md',
  DOCS = 'https://docs.tact-lang.org',
  DOCSSTART = 'https://docs.tact-lang.org/#start',
  PHILOSOPHY = 'https://github.com/tact-lang/tact#10-commandments-of-tact',
  GITHUB = 'https://github.com/tact-lang',
  TELEGRAM = 'https://t.me/tactlang',
  KITCHEN = 'https://t.me/tact_kitchen',
  TON = 'https://ton.org/',
  TWITTER = 'http://twitter.com/tact_language',
  BRAND_ASSETS = 'https://drive.google.com/drive/folders/1Tg1aNg1VqcyiNk26V6IzcHYtsncQWahl?usp=drive_link',
  PLAYGROUND = 'https://tact-by-example.org/all',
  IDE = 'https://ide.ton.org',
  TB_202501_REVIEW = 'https://tact-lang.org/assets/pdfs/2025-01-ton-studio-tact-compiler-securityreview.pdf',
}
